Failed to import the site module
Traceback (most recent call last):
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 523, in main
    known_paths = addsitepackages(known_paths)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 320, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 171, in addpackage
    dir, dircase = makepath(sitedir, line)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 93, in makepath
    dir = os.path.abspath(dir)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/posixpath.py", line 378, in abspath
    return normpath(path)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/posixpath.py", line 366, in normpath
    return path or dot
KeyboardInterrupt
