Failed to import the site module
Traceback (most recent call last):
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 523, in main
    known_paths = addsitepackages(known_paths)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 320, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/types.py", line 171, in <module>
    import functools as _functools
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/collections/__init__.py", line 32, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/reprlib.py", line 163, in <module>
    aRepr = Repr()
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/reprlib.py", line 44, in __init__
    self.maxlist = 6
KeyboardInterrupt
