Failed to import the site module
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1096, in _path_importer_cache
KeyError: '/home/yuntian/anaconda3/envs/main/lib/python3.6/site-packages/transformers-2.2.1-py3.6.egg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 529, in main
    execsitecustomize()
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 473, in execsitecustomize
    import sitecustomize
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1126, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1098, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1074, in _path_hooks
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/encodings/__init__.py", line 100, in search_function
    level=0)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/encodings/cp437.py", line 17, in <module>
    class IncrementalEncoder(codecs.IncrementalEncoder):
KeyboardInterrupt
