Exception ignored in: <function _get_module_lock.<locals>.cb at 0x7fcecff411e0>
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 177, in cb
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/yuntian/Dropbox/Terminal/jzhou/C1GamesStarterKit/generate-train-algo/algo_strategy.py", line 7, in <module>
    import torch
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site-packages/torch/__init__.py", line 280, in <module>
    from .functional import *
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site-packages/torch/functional.py", line 2, in <module>
    import torch.nn.functional as F
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 5, in <module>
    from .. import functional as F
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site-packages/torch/nn/functional.py", line 14, in <module>
    from .._jit_internal import boolean_dispatch, List
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site-packages/torch/_jit_internal.py", line 531, in <module>
    import typing
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/typing.py", line 1945, in <module>
    class ContextManager(Generic[T_co], extra=contextlib.AbstractContextManager):
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/typing.py", line 981, in __new__
    self.__parameters__ = tvars
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/typing.py", line 1167, in __setattr__
    attr.startswith('__') and attr.endswith('__') or
KeyboardInterrupt
